Player.create!([
  #Active Roster
  { 
    name: 'Josh Downs', 
    number: '1', 
    position: 'WR', 
    exp: 0, 
    status: 'Active', 
    college: 'North Carolina', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4688813.png&w=350&h=254', 
    rec: 28, 
    rec_yards: 276, 
    rec_td: 1 
  },
  { 
    name: 'Amari Rodgers', 
    number: '3', 
    position: 'WR', 
    exp: 3, 
    status: 'Active', 
    college: 'Clemson', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4239992.png&w=350&h=254' 
  },
  { 
    name: 'Sam Ehlinger', 
    number: '4', 
    position: 'QB', 
    exp: 3, 
    status: 'Active', 
    college: 'Texas', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4241820.png&w=350&h=254' 
  },
  { 
    name: 'Isaiah McKenzie', 
    number: '6', 
    position: 'WR', 
    exp: 7, 
    status: 'Active', 
    college: 'Georgia', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3128724.png&w=350&h=254', 
    rec: 5, 
    rec_yards: 39, 
    rec_td: 0, 
    rush_att: 1, 
    rush_yds: 4, 
    rush_ypc: 4.0,
    rush_td: 0,
    pr_ret: 9,
    pr_fc: 9,
    pr_yds_ret: 11.0,
    pr_lng: 32,
    pr_td: 0,
    kr_ret: 1,
    kr_fc: 2,
    kr_yds_ret: 19.0,
    kr_lng: 19,
    kr_td: 0
  },
  { 
    name: 'Matt Gay', 
    number: '7', 
    position: 'K', 
    exp: 5, 
    status: 'Active', 
    college: 'Utah', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4249087.png&w=350&h=254',
    fg_1to19: '0',
    fg_20to29: '2-2',
    fg_30to39: '2-2',
    fg_40to49: '2-3',
    fg_50to59: '5-5',
    fg_60Plus: '0'
  },
  { 
    name: 'Rigoberto Sanchez', 
    number: '8', 
    position: 'P', 
    exp: 7, 
    status: 'Active', 
    college: 'Hawaii', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3914922.png&w=350&h=254',
    punt: 25,
    punt_yards: 1139,
    punt_in20: 8,
    punt_avg: 45.56,
    punt_lng: 54
  },
  { 
    name: 'Gardner Minshew', 
    number: '10', 
    position: 'QB', 
    exp: 5, 
    status: 'Active', 
    college: 'Washington State', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4038524.png&w=350&h=254', 
    pass_att: 138, 
    comp: 90, 
    pass_yards: 882, 
    pass_td: 3, 
    int: 3, 
    qb_rtng: 81.25,
    rush_att: 6, 
    rush_yds: 8, 
    rush_ypc: 1.3,
    rush_td: 0
  },
  { 
    name: 'Michael Pittman Jr.', 
    number: '11', 
    position: 'WR', 
    exp: 4, 
    status: 'Active', 
    college: 'USC', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4035687.png&w=350&h=254', 
    rec: 40, 
    rec_yards: 406, 
    rec_td: 1 
  },
  { 
    name: 'Alec Pierce', 
    number: '14', 
    position: 'WR', 
    exp: 2, 
    status: 'Active', 
    college: 'Cincinnati', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4360078.png&w=350&h=254', 
    rec: 11, 
    rec_yards: 149, 
    rec_td: 0
  },
  { 
    name: 'Nick Cross', 
    number: '20', 
    position: 'S', 
    exp: 2, 
    status: 'Active', 
    college: 'Maryland', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4426403.png&w=350&h=254',
    tackles: 6,
    solo_tackles: 6,
    assist: 0,
    def_sacks: 0.0,
    safety: 0,
    def_fumble: 0
  },
  {
    name: 'Zack Moss', 
    number: '21', 
    position: 'RB', 
    exp: 4, 
    status: 'Active', 
    college: 'Utah', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4035676.png&w=350&h=254', 
    rec: 14, 
    rec_yards: 110, 
    rec_td: 1, 
    rush_att: 96, 
    rush_yds: 466, 
    rush_ypc: 4.8,
    rush_td: 4
  },
  { 
    name: 'Kenny Moore II', 
    number: '23', 
    position: 'CB', 
    exp: 7, 
    status: 'Active', 
    college: 'Valdosta State', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4218312.png&w=350&h=254',
    tackles: 36,
    solo_tackles: 27,
    assist: 9,
    def_sacks: 0.0,
    safety: 0,
    def_fumble: 0,
    def_int: 1,
    def_td: 0
  },
  { 
    name: 'Rodney Thomas II', 
    number: '25', 
    position: 'S', 
    exp: 2, 
    status: 'Active', 
    college: 'Yale', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4248455.png&w=350&h=254',
    tackles: 17,
    solo_tackles: 14,
    assist: 3,
    def_sacks: 0.0,
    safety: 0,
    def_fumble: 0 
  },
  { 
    name: 'Trey Sermon', 
    number: '27', 
    position: 'RB', 
    exp: 3, 
    status: 'Active', 
    college: 'Ohio State', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4241401.png&w=350&h=254', 
    rec: 1, 
    rec_yards: 4, 
    rec_td: 0, 
    rush_att: 8, 
    rush_yds: 24, 
    rush_ypc: 3.0,
    rush_td: 0 
  },
  { 
    name: 'Jonathan Taylor', 
    number: '28', 
    position: 'RB', 
    exp: 4, 
    status: 'PUP', 
    college: 'Wisconsin', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4242335.png&w=350&h=254', 
    rec: 6, 
    rec_yards: 62, 
    rec_td: 0, 
    rush_att: 14, 
    rush_yds: 37, 
    rush_ypc: 2.6,
    rush_td: 0 
  },
  { 
    name: 'JuJu Brents', 
    number: '29', 
    position: 'CB', 
    exp: 0, 
    status: 'Active', 
    college: 'Kansas State', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4360488.png&w=350&h=254',
    tackles: 24,
    solo_tackles: 20,
    assist: 4,
    def_sacks: 0.0,
    safety: 0,
    def_fumble: 1,
    def_int: 1
  },
  { 
    name: 'Julian Blackmon', 
    number: '32', 
    position: 'S', 
    exp: 4, 
    status: 'Active', 
    college: 'Utah', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4035661.png&w=350&h=254',
    tackles: 45,
    solo_tackles: 31,
    assist: 14,
    def_sacks: 0.0,
    safety: 0,
    def_fumble: 0,
    def_int: 1,
    def_td: 0
  },
  { 
    name: 'Tony Brown', 
    number: '38', 
    position: 'CB', 
    exp: 5, 
    status: 'Active', 
    college: 'Alabama', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3115308.png&w=350&h=254',
    def_int: 1,
    def_td: 0
  },
  { 
    name: 'Darrell Baker Jr.', 
    number: '39', 
    position: 'CB', 
    exp: 1, 
    status: 'Active', 
    college: 'Georgia Southern', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4036660.png&w=350&h=254',
    tackles: 7,
    solo_tackles: 6,
    assist: 1,
    def_sacks: 0.0,
    safety: 0,
    def_fumble: 0 
  },
  { 
    name: 'Jaylon Jones', 
    number: '40', 
    position: 'CB', 
    exp: 0, 
    status: 'Active', 
    college: 'Texas A&M', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4685145.png&w=350&h=254',
    tackles: 63,
    solo_tackles: 2,
    assist: 1 
  },
  { 
    name: 'Grant Stuard', 
    number: '41', 
    position: 'LB', 
    exp: 3, 
    status: 'Active', 
    college: 'Houston', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4240255.png&w=350&h=254',
    tackles: 5,
    solo_tackles: 4,
    assist: 1,
    def_sacks: 0.0,
    safety: 0,
    def_fumble: 0 
  },
  { 
    name: 'Trevor Denbow', 
    number: '43', 
    position: 'S', 
    exp: 2, 
    status: 'Active', 
    college: 'SMU', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4360538.png&w=350&h=254',
    tackles: 4,
    solo_tackles: 2,
    assist: 2 
  },
  { 
    name: 'Zaire Franklin', 
    number: '44', 
    position: 'LB', 
    exp: 6, 
    status: 'Active', 
    college: 'Syracuse', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3124005.png&w=350&h=254',
    tackles: 77,
    solo_tackles: 49,
    assist: 28,
    def_sacks: 1.5,
    safety: 0,
    def_fumble: 1
  },
  { 
    name: 'E.J. Speed', 
    number: '45', 
    position: 'LB', 
    exp: 5, 
    status: 'Active', 
    college: 'Tarleton State', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3071353.png&w=350&h=254',
    tackles: 28,
    solo_tackles: 20,
    assist: 8,
    def_sacks: 1.0,
    safety: 0,
    def_fumble: 1 
  },
  { 
    name: 'Luke Rhodes', 
    number: '46', 
    position: 'LS', 
    exp: 7, 
    status: 'Active', 
    college: 'William & Mary', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2566045.png&w=350&h=254' 
  },
  { 
    name: 'Segun Olubi', 
    number: '50', 
    position: 'LB', 
    exp: 1, 
    status: 'Active', 
    college: 'San Diego State', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4260703.png&w=350&h=254',
    tackles: 5,
    solo_tackles: 3,
    assist: 2,
    def_sacks: 0.0,
    safety: 0,
    def_fumble: 0 
  },
  { 
    name: 'Kwity Paye', 
    number: '51', 
    position: 'DE', 
    exp: 3, 
    status: 'Active', 
    college: 'Michigan', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4258194.png&w=350&h=254',
    tackles: 14,
    solo_tackles: 9,
    assist: 5,
    def_sacks: 3.0,
    safety: 0,
    def_fumble: 0 
  },
  { 
    name: 'Samson Ebukam', 
    number: '52', 
    position: 'DE', 
    exp: 7, 
    status: 'Active', 
    college: 'Eastern Washington', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3045527.png&w=350&h=254',
    tackles: 19,
    solo_tackles: 15,
    assist: 4,
    def_sacks: 4.0,
    safety: 0,
    def_fumble: 1 
  },
  { 
    name: 'Shaquille Leonard', 
    number: '53', 
    position: 'LB', 
    exp: 6, 
    status: 'Active', 
    college: 'South Carolina State', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3056362.png&w=350&h=254',
    tackles: 28,
    solo_tackles: 16,
    assist: 12,
    def_sacks: 0.0,
    safety: 0,
    def_fumble: 0 
  },
  { 
    name: 'Dayo Odeyingbo', 
    number: '54', 
    position: 'DE', 
    exp: 3, 
    status: 'Active', 
    college: 'Vanderbilt', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4242659.png&w=350&h=254',
    tackles: 14,
    solo_tackles: 8,
    assist: 6,
    def_sacks: 1.5,
    safety: 0,
    def_fumble: 2 
  },
  { 
    name: 'Isaiah Land', 
    number: '55', 
    position: 'LB', 
    exp: 0, 
    status: 'Active', 
    college: 'Florida A&M', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4574551.png&w=350&h=254',
    assist: 1
  },
  { 
    name: 'Quenton Nelson', 
    number: '56', 
    position: 'G', 
    exp: 6, 
    status: 'Active', 
    college: 'Notre Dame', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3129308.png&w=350&h=254' 
  },
  { 
    name: 'Cameron McGrone', 
    number: '59', 
    position: 'LB', 
    exp: 1, 
    status: 'Active', 
    college: 'Michigan', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4372085.png&w=350&h=254' 
  },
  { 
    name: 'Wesley French', 
    number: '62', 
    position: 'C', 
    exp: 2, 
    status: 'Active', 
    college: 'Western Michigan', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3916746.png&w=350&h=254' 
  },
  { 
    name: 'Arlington Hambright', 
    number: '64', 
    position: 'G', 
    exp: 6, 
    status: 'Active', 
    college: 'Colorado', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4241422.png&w=350&h=254' 
  },
  { 
    name: 'Josh Sills', 
    number: '65', 
    position: 'G', 
    exp: 2, 
    status: 'Active', 
    college: 'Oklahoma State', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4039243.png&w=350&h=254' 
  },
  { 
    name: 'Ike Boettger', 
    number: '68', 
    position: 'G', 
    exp: 6, 
    status: 'Active', 
    college: 'Iowa', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3040166.png&w=350&h=254' 
  },
  { 
    name: 'Braden Smith', 
    number: '72', 
    position: 'T', 
    exp: 6, 
    status: 'Active', 
    college: 'Auburn', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3121595.png&w=350&h=254' 
  },
  { 
    name: 'Blake Freeland', 
    number: '73', 
    position: 'T', 
    exp: 0, 
    status: 'Active', 
    college: 'BYU', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4429636.png&w=350&h=254' 
  },
  { 
    name: 'Will Fries', 
    number: '75', 
    position: 'C/G', 
    exp: 3, 
    status: 'Active', 
    college: 'Penn Statee', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4045176.png&w=350&h=254' 
  },
  { 
    name: 'Ryan Kelly', 
    number: '78', 
    position: 'C', 
    exp: 8, 
    status: 'Active', 
    college: 'Alabama', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2578475.png&w=350&h=254' 
  },
  { 
    name: 'Bernhard Raimann', 
    number: '79', 
    position: 'T', 
    exp: 2, 
    status: 'Active', 
    college: 'Central Michigan', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4362580.png&w=350&h=254' 
  },
  { 
    name: 'Mo Alie-Cox', 
    number: '81', 
    position: 'TE', 
    exp: 6, 
    status: 'Active', 
    college: 'Virginia Commonwealth', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2998565.png&w=350&h=254', 
    rec: 3, 
    rec_yards: 67, 
    rec_td: 1 
  },
  { 
    name: 'Kylen Granson', 
    number: '83', 
    position: 'TE', 
    exp: 3, 
    status: 'Active', 
    college: 'SMU', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4039160.png&w=350&h=254', 
    rec: 16, 
    rec_yards: 170, 
    rec_td: 1 
  },
  { 
    name: 'Andrew Ogletree', 
    number: '85', 
    position: 'TE', 
    exp: 2, 
    status: 'Active', 
    college: 'Youngstown State', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4722908.png&w=350&h=254', 
    rec: 7, 
    rec_yards: 95, 
    rec_td: 1 
  },
  { 
    name: 'Will Mallory', 
    number: '86', 
    position: 'TE', 
    exp: 0, 
    status: 'Active', 
    college: 'Miami', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4362523.png&w=350&h=254', 
    rec: 2, 
    rec_yards: 49, 
    rec_td: 0 
  },
  { 
    name: 'Grover Stewart', 
    number: '90', 
    position: 'DT', 
    exp: 7, 
    status: 'Active', 
    college: 'Albany State', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4058825.png&w=350&h=254',
    tackles: 20,
    solo_tackles: 13,
    assist: 7,
    def_sacks: 0.0,
    safety: 0,
    def_fumble: 0 
  },
  { 
    name: 'Jake Martin', 
    number: '92', 
    position: 'DE', 
    exp: 6, 
    status: 'Active', 
    college: 'Temple', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3138764.png&w=350&h=254',
    tackles: 2,
    solo_tackles: 1,
    assist: 1 
  },
  { 
    name: 'Eric Johnson II', 
    number: '93', 
    position: 'DT', 
    exp: 2, 
    status: 'Active', 
    college: 'Missouri State', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4050971.png&w=350&h=254',
    tackles: 6,
    solo_tackles: 3,
    assist: 3,
    def_sacks: 0.0,
    safety: 0,
    def_fumble: 0 
  },
  { 
    name: 'Tyquan Lewis', 
    number: '94', 
    position: 'DE', 
    exp: 6, 
    status: 'Active', 
    college: 'Ohio State', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3040513.png&w=350&h=254',
    tackles: 6,
    solo_tackles: 5,
    assist: 1,
     def_sacks: 1.0
  },
  { 
    name: 'Adetomiwa Adebawore', 
    number: '95', 
    position: 'DT', 
    exp: 0, 
    status: 'Active', 
    college: 'Northwestern', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4427635.png&w=350&h=254' 
  },
  { 
    name: 'Taven Bryan', 
    number: '96', 
    position: 'DT', 
    exp: 6, 
    status: 'Active', 
    college: 'Florida', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3115249.png&w=350&h=254',
    tackles: 12,
    solo_tackles: 9,
    assist: 3,
    def_sacks: 2.0,
    safety: 0,
    def_fumble: 1 
  },
  { 
    name: 'DeForest Buckner', 
    number: '99', 
    position: 'DT', 
    exp: 8, 
    status: 'Active', 
    college: 'Oregon', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2971282.png&w=350&h=254',
    tackles: 24,
    solo_tackles: 12,
    assist: 12,
    def_sacks: 3.0,
    safety: 0,
    def_fumble: 1 
  }
])