Player.create!([
  #Active Roster
  { name: 'Michael Tutsie', number: '--', position: 'S', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Josh Downs', number: '1', position: 'WR', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Zavier Scott', number: '2', position: 'WR', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Johnny King', number: '3', position: 'WR', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Lucas Havrisik', number: '3', position: 'K', exp: 1, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Sam Ehlinger', number: '4', position: 'QB', exp: 3, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4241820.png&w=350&h=254' },
  { name: 'Anthony Richardson', number: '5', position: 'QB', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Isaiah McKenzie', number: '6', position: 'WR', exp: 7, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3128724.png&w=350&h=254' },
  { name: 'Matt Gay', number: '7', position: 'K', exp: 5, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4249087.png&w=350&h=254' },
  { name: 'Juwann Winfree', number: '8', position: 'WR', exp: 3, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3128317.png&w=350&h=254' },
  { name: 'Rigoberto Sanchez', number: '8', position: 'P', exp: 7, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3914922.png&w=350&h=254' },
  { name: 'Breshad Perriman', number: '9', position: 'WR', exp: 9, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2972460.png&w=350&h=254' },
  { name: 'Gardner Minshew', number: '10', position: 'QB', exp: 5, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4038524.png&w=350&h=254' },
  { name: 'Michael Pittman Jr.', number: '11', position: 'WR', exp: 4, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4035687.png&w=350&h=254' },
  { name: 'Malik Turner', number: '12', position: 'WR', exp: 5, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3115928.png&w=350&h=254' },
  { name: 'Kody Case', number: '13', position: 'WR', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Alec Pierce', number: '14', position: 'WR', exp: 2, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4360078.png&w=350&h=254' },
  { name: 'Ashton Dulin', number: '16', position: 'WR', exp: 5, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4061956.png&w=350&h=254' },
  { name: 'Mike Strachan', number: '17', position: 'WR', exp: 3, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4589245.png&w=350&h=254' },
  { name: 'Nick Cross', number: '20', position: 'S', exp: 2, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4426403.png&w=350&h=254' },
  { name: 'Zack Moss', number: '21', position: 'RB', exp: 4, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4035676.png&w=350&h=254' },
  { name: 'Kenny Moore II', number: '23', position: 'CB', exp: 7, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4218312.png&w=350&h=254' },
  { name: 'Rodney Thomas II', number: '25', position: 'S', exp: 2, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4248455.png&w=350&h=254' },
  { name: 'Evan Hull', number: '26', position: 'RB', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Kevin Toliver II', number: '27', position: 'CB', exp: 4, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3843234.png&w=350&h=254' },
  { name: 'Jonathan Taylor', number: '28', position: 'RB', exp: 4, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4242335.png&w=350&h=254' },
  { name: 'Julius Brents', number: '29', position: 'CB', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Darius Rush', number: '30', position: 'CB', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Daniel Scott', number: '31', position: 'S', exp: 0, status: 'IR', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Julian Blackmon', number: '32', position: 'S', exp: 4, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4035661.png&w=350&h=254' },
  { name: 'Dallis Flowers', number: '33', position: 'CB', exp: 2, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4917592.png&w=350&h=254' },
  { name: 'Chris Lammons', number: '33', position: 'CB', exp: 4, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3128630.png&w=350&h=254' },
  { name: 'Deon Jackson', number: '35', position: 'RB', exp: 3, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4240455.png&w=350&h=254' },
  { name: 'Henry Black', number: '36', position: 'S', exp: 3, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3928920.png&w=350&h=254' },
  { name: 'Jake Funk', number: '37', position: 'RB', exp: 3, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4036224.png&w=350&h=254' },
  { name: 'Isaac Taylor-Stuart', number: '38', position: 'CB', exp: 2, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4374301.png&w=350&h=254' },
  { name: 'Tony Brown', number: '38', position: 'CB', exp: 5, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3115308.png&w=350&h=254' },
  { name: 'Darrell Baker Jr.', number: '39', position: 'CB', exp: 1, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4036660.png&w=350&h=254' },
  { name: 'Jaylon Jones', number: '40', position: 'CB', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Grant Stuard', number: '41', position: 'LB', exp: 3, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4240255.png&w=350&h=254' },
  { name: 'Marcel Dabo', number: '42', position: 'S', exp: 1, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/5054377.png&w=350&h=254' },
  { name: 'Trevor Denbow', number: '43', position: 'S', exp: 2, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4360538.png&w=350&h=254' },
  { name: 'Zaire Franklin', number: '44', position: 'LB', exp: 6, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3124005.png&w=350&h=254' },
  { name: 'E.J. Speed', number: '45', position: 'LB', exp: 5, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3071353.png&w=350&h=254' },
  { name: 'Luke Rhodes', number: '46', position: 'LS', exp: 7, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2566045.png&w=350&h=254' },
  { name: 'Liam Anderson', number: '47', position: 'LB', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Aaron Maddox', number: '48', position: 'S', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Kaden Smith', number: '48', position: 'TE', exp: 4, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4044452.png&w=350&h=254' },
  { name: 'Pharaoh Brown', number: '49', position: 'TE', exp: 6, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2971281.png&w=350&h=254' },
  { name: 'Segun Olubi', number: '50', position: 'LB', exp: 1, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4260703.png&w=350&h=254' },
  { name: 'Kwity Paye', number: '51', position: 'DE', exp: 3, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4258194.png&w=350&h=254' },
  { name: 'Samson Ebukam', number: '52', position: 'LB', exp: 7, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3045527.png&w=350&h=254' },
  { name: 'Shaquille Leonard', number: '53', position: 'LB', exp: 6, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3056362.png&w=350&h=254' },
  { name: 'Dayo Odeyingbo', number: '54', position: 'DE', exp: 3, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4242659.png&w=350&h=254' },
  { name: 'Quenton Nelson', number: '56', position: 'G', exp: 6, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3129308.png&w=350&h=254' },
  { name: 'JoJo Domann', number: '57', position: 'LB', exp: 2, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4034841.png&w=350&h=254' },
  { name: 'Donavan Mutin', number: '58', position: 'LB', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Cameron McGrone', number: '59', position: 'LB', exp: 1, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4372085.png&w=350&h=254' },
  { name: 'Matthew Vanderslice', number: '60', position: 'T', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Carter O\'Donnell', number: '61', position: 'T', exp: 2, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4611135.png&w=350&h=254' },
  { name: 'Wesley French', number: '62', position: 'C', exp: 2, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3916746.png&w=350&h=254' },
  { name: 'Danny Pinter', number: '63', position: 'G', exp: 4, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3915470.png&w=350&h=254' },
  { name: 'Arlington Hambright', number: '64', position: 'G', exp: 2, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4241422.png&w=350&h=254' },
  { name: 'Dakoda Shepley', number: '65', position: 'C', exp: 2, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4335942.png&w=350&h=254' },
  { name: 'Emil Ekiyor', number: '66', position: 'G', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Caleb Sampson', number: '68', position: 'DT', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Jamal Woods', number: '69', position: 'DT', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Jordan Murray', number: '71', position: 'T', exp: 1, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3914494.png&w=350&h=254' },
  { name: 'Braden Smith', number: '72', position: 'T', exp: 6, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3121595.png&w=350&h=254' },
  { name: 'Blake Freeland', number: '73', position: 'T', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Will Fries', number: '75', position: 'G/T', exp: 3, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4045176.png&w=350&h=254' },
  { name: 'Jake Witt', number: '76', position: 'T', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Ryan Kelly', number: '78', position: 'C', exp: 8, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2578475.png&w=350&h=254' },
  { name: 'Bernhard Raimann', number: '79', position: 'T', exp: 2, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4362580.png&w=350&h=254' },
  { name: 'Jelani Woods', number: '80', position: 'TE', exp: 2, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4241410.png&w=350&h=254' },
  { name: 'Mo Alie-Cox', number: '81', position: 'TE', exp: 6, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2998565.png&w=350&h=254' },
  { name: 'Kylen Granson', number: '83', position: 'TE', exp: 3, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4039160.png&w=350&h=254' },
  { name: 'Andrew Ogletree', number: '85', position: 'TE', exp: 2, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4722908.png&w=350&h=254' },
  { name: 'Will Mallory', number: '86', position: 'TE', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Vycint Smith', number: '86', position: 'WR', exp: 4, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3155188.png&w=350&h=254' },
  { name: 'Grover Stewart', number: '90', position: 'DT', exp: 7, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4058825.png&w=350&h=254' },
  { name: 'Titus Leo', number: '91', position: 'DE', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Genard Avery', number: '92', position: 'DE', exp: 6, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3126204.png&w=350&h=254' },
  { name: 'Eric Johnson', number: '93', position: 'DT', exp: 2, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4050971.png&w=350&h=254' },
  { name: 'Tyquan Lewis', number: '94', position: 'DE', exp: 6, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3040513.png&w=350&h=254' },
  { name: 'Adetomiwa Adebawore', number: '95', position: 'DE', exp: 0, status: 'Active', photo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png' },
  { name: 'Taven Bryan', number: '96', position: 'DT', exp: 6, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3115249.png&w=350&h=254' },
  { name: 'Al-Quadin Muhammad', number: '97', position: 'DE', exp: 7, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3051942.png&w=350&h=254' },
  { name: 'McTelvin Agim', number: '98', position: 'DT', exp: 3, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4035566.png&w=350&h=254' },
  { name: 'DeForest Buckner', number: '99', position: 'DT', exp: 8, status: 'Active', photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2971282.png&w=350&h=254' }
  # Injured/Reserve
  # Practice Squad
])