Player.create!([
  #Active Roster
  {
    name: 'Cam Bynum',
    number: '0',
    position: 'S',
    exp: 5,
    status: 'Active',
    college: 'California',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4035861.png&w=350&h=254',
  },
  {
    name: 'Josh Downs',
    number: '1',
    position: 'WR',
    exp: 3,
    status: 'Active',
    college: 'North Carolina',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4688813.png&w=350&h=254',
  },
  {
    name: 'D.J. Montgomery',
    number: '2',
    position: 'WR',
    exp: 3,
    status: 'IR',
    college: 'Austin Peay',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4249030.png&w=350&h=254'
  },
  {
    name: 'Spencer Shrader',
    number: '3',
    position: 'K',
    exp: 2,
    status: 'Active',
    college: 'Notre Dame',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4571557.png&w=350&h=254',
  },
  {
    name: 'Coleman Owen',
    number: '3',
    position: 'WR',
    exp: 0,
    status: 'Active',
    college: 'Ohio',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ind.png&h=200&w=200',
  },
  {
    name: 'Blayne Taylor',
    number: '4',
    position: 'WR',
    exp: 0,
    status: 'Active',
    college: 'Abilene CHristian',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ind.png&h=200&w=200',
  },
  {
    name: 'Mekhi Blackmon',
    number: '5',
    position: 'CB',
    exp: 3,
    status: 'Active',
    college: 'USC',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4360677.png&w=350&h=254',
  },
  {
    name: 'Anthony Richardson Sr.',
    number: '5',
    position: 'QB',
    exp: 3,
    status: 'Active',
    college: 'Florida',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4429084.png&w=350&h=254',
  },
  {
    name: 'Anthony Gould',
    number: '6',
    position: 'WR',
    exp: 2,
    status: 'Active',
    college: 'Oregon State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4429684.png&w=350&h=254',
  },
  {
    name: 'Charvarius Ward',
    number: '7',
    position: 'CB',
    exp: 8,
    status: 'Active',
    college: 'Middle Tennessee State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4037361.png&w=350&h=254',
  },
  {
    name: 'Rigoberto Sanchez',
    number: '8',
    position: 'P',
    exp: 9,
    status: 'Active',
    college: 'Hawaii',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3914922.png&w=350&h=254',
  },
  {
    name: 'Jason Bean',
    number: '8',
    position: 'QB/WR',
    exp: 2,
    status: 'Active',
    college: 'Kansas',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4360900.png&w=350&h=254'
  },
  {
    name: 'Landon Parker',
    number: '8',
    position: 'WR',
    exp: 0,
    status: 'Active',
    college: 'Troy',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4370170.png&w=350&h=254',
  },
  {
    name: 'Ajou Ajou',
    number: '9',
    position: 'WR',
    exp: 0,
    status: 'Active',
    college: 'South Florida',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4429207.png&w=350&h=254'
  },
  {
    name: 'Adonai Mitchell',
    number: '10',
    position: 'WR',
    exp: 2,
    status: 'Active',
    college: 'Texas',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4597500.png&w=350&h=254',
  },
  {
    name: 'Michael Pittman Jr.',
    number: '11',
    position: 'WR',
    exp: 6,
    status: 'Active',
    college: 'USC',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4035687.png&w=350&h=254',
  },
  {
    name: 'Laquon Treadwell',
    number: '13',
    position: 'WR',
    exp: 9,
    status: 'Active',
    college: 'Mississippi',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3051889.png&w=350&h=254'
  },
  {
    name: 'Alec Pierce',
    number: '14',
    position: 'WR',
    exp: 4,
    status: 'Active',
    college: 'Cincinnati',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4360078.png&w=350&h=254',
  },
  {
    name: 'Riley Leonard',
    number: '15',
    position: 'QB',
    exp: 0,
    status: 'Active',
    college: 'Notre Dame',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4683423.png&w=350&h=254',
  },
  {
    name: 'Ashton Dulin',
    number: '16',
    position: 'WR',
    exp: 7,
    status: 'Active',
    college: 'Malone University',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4061956.png&w=350&h=254',
  },
  {
    name: 'Daniel Jones',
    number: '17',
    position: 'QB',
    exp: 7,
    status: 'Active',
    college: 'Duke',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3917792.png&w=350&h=254',
  },
  {
    name: 'Nick Cross',
    number: '20',
    position: 'S',
    exp: 4,
    status: 'Active',
    college: 'Maryland',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4426403.png&w=350&h=254',
  },
  {
    name: 'DJ Giddens',
    number: '21',
    position: 'RB',
    exp: 0,
    status: 'Active',
    college: 'Kansas State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4874509.png&w=350&h=254',
  },
  {
    name: 'Kenny Moore II',
    number: '23',
    position: 'CB',
    exp: 9,
    status: 'Active',
    college: 'Valdosta State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4218312.png&w=350&h=254',
  },
  {
    name: 'Rodney Thomas II',
    number: '25',
    position: 'S',
    exp: 4,
    status: 'Active',
    college: 'Yale',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4248455.png&w=350&h=254',
  },
  {
    name: 'Khalil Herbert',
    number: '26',
    position: 'RB',
    exp: 5,
    status: 'Active',
    college: 'Virginia Tech',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4035886.png&w=350&h=254',
  },
  {
    name: 'Justin Walley',
    number: '27',
    position: 'CB',
    exp: 0,
    status: 'IR',
    college: 'Minnesota',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4682909.png&w=350&h=254',
  },
  {
    name: 'Jonathan Taylor',
    number: '28',
    position: 'RB',
    exp: 6,
    status: 'Active',
    college: 'Wisconsin',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4242335.png&w=350&h=254',
  },
  {
    name: 'JuJu Brents',
    number: '29',
    position: 'CB',
    exp: 3,
    status: 'Active',
    college: 'Kansas State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4360488.png&w=350&h=254',
  },
  {
    name: 'Hunter Wohler',
    number: '30',
    position: 'S',
    exp: 0,
    status: 'IR',
    college: 'Wisconsin',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4432789.png&w=350&h=254',
  },
  {
    name: 'Tyler Goodson',
    number: '31',
    position: 'RB',
    exp: 3,
    status: 'Active',
    college: 'Iowa',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4429676.png&w=350&h=254',
  },
  {
    name: 'Daniel Scott',
    number: '32',
    position: 'S',
    exp: 3,
    status: 'Active',
    college: 'California',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4242415.png&w=350&h=254'
  },
  {
    name: 'Samuel Womack III',
    number: '33',
    position: 'CB',
    exp: 4,
    status: 'Active',
    college: 'Toledo',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4280416.png&w=350&h=254',
  },
  {
     name: 'David Long',
     number: '34',
     position: 'CB',
     exp: 7,
     status: 'IR',
     college: 'Michigan',
     photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4046536.png&w=350&h=254'
  },
  {
    name: 'Duke Shelley',
    number: '34',
    position: 'CB',
    exp: 6,
    status: 'Active',
    college: 'Kansas State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3916126.png&w=350&h=254',
  },
  {
    name: 'Johnathan Edwards',
    number: '35',
    position: 'CB',
    exp: 0,
    status: 'Active',
    college: 'Tulane',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4695991.png&w=350&h=254',
  },
  {
    name: 'Salvon Ahmed',
    number: '36',
    position: 'RB',
    exp: 5,
    status: 'IR',
    college: 'Washington',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4243315.png&w=350&h=254'
  },
  {
    name: 'BJ Mayes',
    number: '36',
    position: 'CB',
    exp: 0,
    status: 'Active',
    college: 'Texas A&M',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4683044.png&w=350&h=254',
  },
  {
    name: 'Ulysses Bentley IV',
    number: '37',
    position: 'RB',
    exp: 0,
    status: 'Active',
    college: 'Mississippi',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4426689.png&w=350&h=254',
  },
  {
    name: 'Xavien Howard',
    number: '37',
    position: 'CB',
    exp: 9,
    status: 'Active',
    college: 'Baylor',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2978935.png&w=350&h=254',
  },
  {
    name: 'Chris Lammons',
    number: '38',
    position: 'CB',
    exp: 5,
    status: 'Active',
    college: 'South Carolina',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3128630.png&w=350&h=254',
  },
  {
    name: 'Alex Johnson',
    number: '39',
    position: 'CB',
    exp: 1,
    status: 'Active',
    college: 'UCLA',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4367181.png&w=350&h=254'
  },
  {
    name: 'Jaylon Jones',
    number: '40',
    position: 'CB',
    exp: 3,
    status: 'Active',
    college: 'Texas A&M',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4685145.png&w=350&h=254',
  },
  {
    name: 'Nate Noel',
    number: '41',
    position: 'RB',
    exp: 0,
    status: 'Active',
    college: 'Missouri',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4613032.png&w=350&h=254',
  },
  {
    name: 'Trey Washington',
    number: '41',
    position: 'S',
    exp: 0,
    status: 'Active',
    college: 'Mississippi',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4599160.png&w=350&h=254',
  },
  {
    name: 'Nay\'Quan Wright',
    number: '42',
    position: 'RB',
    exp: 0,
    status: 'Active',
    college: 'South Florida',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4567400.png&w=350&h=254',
  },
  {
    name: 'Tyler Kahmann',
    number: '43',
    position: 'WR',
    exp: 0,
    status: 'Active',
    college: 'Emporia State University',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ind.png&h=200&w=200',
  },
  {
    name: 'Ladarius Tennison',
    number: '43',
    position: 'S',
    exp: 0,
    status: 'Active',
    college: 'UCF',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4433922.png&w=350&h=254',
  },
  {
    name: 'Zaire Franklin',
    number: '44',
    position: 'LB',
    exp: 8,
    status: 'Active',
    college: 'Syracuse',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3124005.png&w=350&h=254',
  },
  {
    name: 'Maximilian Mang',
    number: '45',
    position: 'TE',
    exp: 0,
    status: 'Active',
    college: 'Syracuse',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4608691.png&w=350&h=254',
  },
  {
    name: 'Luke Rhodes',
    number: '46',
    position: 'LS',
    exp: 9,
    status: 'Active',
    college: 'William & Mary',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2566045.png&w=350&h=254'
  },
  {
    name: 'Jake Chaney',
    number: '47',
    position: 'LB',
    exp: 0,
    status: 'Active',
    college: 'Wisconsin',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ind.png&h=200&w=200',
  },
  {
    name: 'Joe Bachie',
    number: '48',
    position: 'LB',
    exp: 6,
    status: 'Active',
    college: 'Michigan State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4036507.png&w=350&h=254'
  },
  {
    name: 'Maddux Trujillo',
    number: '48',
    position: 'K',
    exp: 0,
    status: 'Active',
    college: 'Temple',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4879326.png&w=350&h=254',
  },
  {
    name: 'Sean McKeon',
    number: '49',
    position: 'TE',
    exp: 5,
    status: 'Active',
    college: 'Michigan',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4036275.png&w=350&h=254'
  },
  {
    name: 'Joseph Vaughn',
    number: '49',
    position: 'LB',
    exp: 0,
    status: 'Active',
    college: 'UCLA',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ind.png&h=200&w=200',
  },
  {
    name: 'Segun Olubi',
    number: '50',
    position: 'LB',
    exp: 3,
    status: 'Active',
    college: 'San Diego State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4260703.png&w=350&h=254',
  },
  {
    name: 'Kwity Paye',
    number: '51',
    position: 'DE',
    exp: 5,
    status: 'Active',
    college: 'Michigan',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4258194.png&w=350&h=254',
  },
  {
    name: 'Samson Ebukam',
    number: '52',
    position: 'DE',
    exp: 9,
    status: 'Active',
    college: 'Eastern Washington',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3045527.png&w=350&h=254'
  },
  {
    name: 'Jacob Phillips',
    number: '53',
    position: 'LB',
    exp: 4,
    status: 'IR',
    college: 'LSU',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4242206.png&w=350&h=254'
  },
  {
    name: 'Solomon DeShields',
    number: '53',
    position: 'LB',
    exp: 0,
    status: 'Active',
    college: 'Texas A&M',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431065.png&w=350&h=254',
  },
  {
    name: 'Isaiah Land',
    number: '55',
    position: 'LB',
    exp: 3,
    status: 'Active',
    college: 'Florida A&M',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4574551.png&w=350&h=254'
  },
  {
    name: 'Quenton Nelson',
    number: '56',
    position: 'G',
    exp: 8,
    status: 'Active',
    college: 'Notre Dame',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3129308.png&w=350&h=254'
  },
  {
    name: 'Jaylon Carlies',
    number: '57',
    position: 'LB',
    exp: 2,
    status: 'Active',
    college: 'Missouri',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4601021.png&w=350&h=254',
  },
  {
    name: 'Austin Ajiake',
    number: '58',
    position: 'LB',
    exp: 1,
    status: 'Active',
    college: 'UNLV',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4374171.png&w=350&h=254'
  },
  {
    name: 'Cameron McGrone',
    number: '59',
    position: 'LB',
    exp: 3,
    status: 'Active',
    college: 'Michigan',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4372085.png&w=350&h=254'
  },
  {
    name: 'Tanor Bortolini',
    number: '60',
    position: 'G',
    exp: 2,
    status: 'Active',
    college: 'Wisconsin',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4430957.png&w=350&h=254'
  },
  {
    name: 'Devonta Davis',
    number: '61',
    position: 'DT',
    exp: 0,
    status: 'Active',
    college: 'Florida Atlantic',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4574833.png&w=350&h=254',
  },
  {
    name: 'Wesley French',
    number: '62',
    position: 'C',
    exp: 4,
    status: 'Active',
    college: 'Western Michigan',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3916746.png&w=350&h=254'
  },
  {
    name: 'Danny Pinter',
    number: '63',
    position: 'G',
    exp: 6,
    status: 'Active',
    college: 'Ball State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3915470.png&w=350&h=254'
  },
  {
    name: 'Marshall Foerner',
    number: '64',
    position: 'OT',
    exp: 0,
    status: 'Active',
    college: 'Minnesota State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ind.png&h=200&w=200',
  },
  {
    name: 'Josh Sills',
    number: '66',
    position: 'G',
    exp: 3,
    status: 'Active',
    college: 'Oklahoma State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4039243.png&w=350&h=254'
  },
  {
    name: 'Luke Tenuta',
    number: '67',
    position: 'T',
    exp: 3,
    status: 'Active',
    college: 'Virginia Tech',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4361979.png&w=350&h=254'
  },
  {
    name: 'Mose Vavao',
    number: '67',
    position: 'C',
    exp: 0,
    status: 'Active',
    college: 'Fresno State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4609783.png&w=350&h=254'
  },
  {
    name: 'Dalton Tucker',
    number: '68',
    position: 'G',
    exp: 2,
    status: 'Active',
    college: 'Marshall',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4370363.png&w=350&h=254'
  },
  {
    name: 'Josh Tupou',
    number: '69',
    position: 'DT',
    exp: 7,
    status: 'Active',
    college: 'Colorado',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2979632.png&w=350&h=254',
  },
  {
    name: 'Matt Goncalves',
    number: '71',
    position: 'T',
    exp: 2,
    status: 'Active',
    college: 'Pittsburgh',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4427298.png&w=350&h=254'
  },
  {
    name: 'Marcellus Johnson',
    number: '71',
    position: 'T',
    exp: 1,
    status: 'Active',
    college: 'Missouri',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4363547.png&w=350&h=254'
  },
  {
    name: 'Braden Smith',
    number: '72',
    position: 'T',
    exp: 8,
    status: 'Active',
    college: 'Auburn',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3121595.png&w=350&h=254'
  },
  {
    name: 'Blake Freeland',
    number: '73',
    position: 'T',
    exp: 3,
    status: 'IR',
    college: 'BYU',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4429636.png&w=350&h=254'
  },
  {
    name: 'Durell Nchami',
    number: '74',
    position: 'DE',
    exp: 1,
    status: 'Active',
    college: 'Maryland',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4360638.png&w=350&h=254'
  },
  {
    name: 'Jalen Travis',
    number: '75',
    position: 'T',
    exp: 0,
    status: 'Active',
    college: 'Iowa State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4892240.png&w=350&h=254'
  },
  {
    name: 'Jack Wilson',
    number: '76',
    position: 'IR',
    exp: 1,
    status: 'Active',
    college: 'Washington State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/504844.png&w=350&h=254'
  },
  {
    name: 'Desmond Little',
    number: '78',
    position: 'DE',
    exp: 0,
    status: 'Active',
    college: 'UAB',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4427813.png&w=350&h=254',
  },
  {
    name: 'Bernhard Raimann',
    number: '79',
    position: 'T',
    exp: 4,
    status: 'Active',
    college: 'Central Michigan',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4362580.png&w=350&h=254',
  },
  {
    name: 'Jelani Woods',
    number: '80',
    position: 'TE',
    exp: 4,
    status: 'Active',
    college: 'Virginia',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4241410.png&w=350&h=254'
  },
  { 
     name: 'Mo Alie-Cox', 
     number: '81', 
     position: 'TE', 
     exp: 8, 
     status: 'Active', 
     college: 'Virginia Commonwealth', 
     photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2998565.png&w=350&h=254',
  },
  {
    name: 'Tyler Warren',
    number: '84',
    position: 'TE',
    exp: 0,
    status: 'Active',
    college: 'Penn State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4431459.png&w=350&h=254',
  },
  {
    name: 'Albert Okwuegbunam',
    number: '84',
    position: 'TE',
    exp: 6,
    status: 'Active',
    college: 'Missouri',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4035115.png&w=350&h=254'
  },
  {
    name: 'Drew Ogletree',
    number: '85',
    position: 'TE',
    exp: 4,
    status: 'Active',
    college: 'Youngstown State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4722908.png&w=350&h=254',
  },
  {
    name: 'Will Mallory',
    number: '86',
    position: 'TE',
    exp: 3,
    status: 'Active',
    college: 'Miami',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4362523.png&w=350&h=254',
  },
  {
    name: 'Grover Stewart',
    number: '90',
    position: 'DT',
    exp: 9,
    status: 'Active',
    college: 'Albany State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4058825.png&w=350&h=254',
  },
  {
    name: 'JT Tuimoloau',
    number: '91',
    position: 'DE',
    exp: 0,
    status: 'Active',
    college: 'Ohio State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4566154.png&w=350&h=254',
  },
  {
    name: 'Neville Gallimore',
    number: '92',
    position: 'DT',
    exp: 6,
    status: 'Active',
    college: 'Oklahoma',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3892883.png&w=350&h=254',
  },
  {
    name: 'Tim Smith',
    number: '93',
    position: 'DT',
    exp: 0,
    status: 'Active',
    college: 'Alabama',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4692033.png&w=350&h=254',
  },
  { 
    name: 'Eric Johnson II', 
    number: '93', 
    position: 'DT', 
    exp: 2, 
    status: 'Active', 
    college: 'Missouri State', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4050971.png&w=350&h=254'
  },
  {
    name: 'Tyquan Lewis',
    number: '94',
    position: 'DE',
    exp: 8,
    status: 'Active',
    college: 'Ohio State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3040513.png&w=350&h=254',
  },
  {
    name: 'Adetomiwa Adebawore',
    number: '95',
    position: 'DT',
    exp: 3,
    status: 'Active',
    college: 'Northwestern',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4427635.png&w=350&h=254',
  },
  {
    name: 'Marcus Haynes',
    number: '96',
    position: 'DE',
    exp: 1,
    status: 'Active',
    college: 'Old Dominion',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4243507.png&w=350&h=254',
  },
  {
    name: 'Laiatu Latu',
    number: '97',
    position: 'DE',
    exp: 1,
    status: 'Active',
    college: 'UCLA',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4426473.png&w=350&h=254',
  },
  {
    name: 'DeForest Buckner',
    number: '99',
    position: 'DT',
    exp: 10,
    status: 'Active',
    college: 'Oregon',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2971282.png&w=350&h=254',
  }
])
