Player.create!([
  #Active Roster
  {
    name: 'Cam Bynum',
    number: '0',
    position: 'S',
    exp: 5,
    status: 'Active',
    college: 'California',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4035861.png&w=350&h=254',
    tackles: 54,
    solo_tackles: 30,
    assist: 24,
    def_sacks: 1,
    def_fumble: 1,
    def_int: 3
  },
  {
    name: 'Sauce Gardner',
    number: '1',
    position: 'CB',
    exp: 4,
    status: 'Active',
    college: 'Cincinnati',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4427250.png&w=350&h=254',
    tackles: 13,
    solo_tackles: 11,
    assist: 2
  },
  {
    name: 'Josh Downs',
    number: '2',
    position: 'WR',
    exp: 3,
    status: 'Active',
    college: 'North Carolina',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4688813.png&w=350&h=254',
    rec: 40,
    rec_yards: 370,
    rec_ypc: 9.2,
    rec_td: 3,
    pr_ret: 6,
    pr_fc: 3,
    pr_lng: 24,
    pr_yds: 9.2
  },
  {
    name: 'D.J. Montgomery',
    number: '2',
    position: 'WR',
    exp: 3,
    status: 'IR',
    college: 'Austin Peay',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4249030.png&w=350&h=254'
  },
  {
    name: 'Spencer Shrader',
    number: '3',
    position: 'K',
    exp: 2,
    status: 'IR',
    college: 'Notre Dame',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4571557.png&w=350&h=254',
    fg_1to19: '0 - 0',
    fg_20to29: '5 - 5',
    fg_30to39: '5 - 5',
    fg_40to49: '2 - 2',
    fg_50to59: '1 - 2',
    fg_60Plus: '0 - 0'
  },
  {
    name: 'Xavien Howard',
    number: '4',
    position: 'CB',
    exp: 9,
    status: 'Retired',
    college: 'Baylor',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2978935.png&w=350&h=254',
    tackles: 11,
    solo_tackles: 7,
    assist: 4
  },
  {
    name: 'Brett Rypien',
    number: '4',
    position: 'QB',
    exp: 7,
    status: 'PS',
    college: 'Boise State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3722362.png&w=350&h=254'
  },
  {
    name: 'Anthony Richardson Sr.',
    number: '5',
    position: 'QB',
    exp: 3,
    status: 'IR',
    college: 'Florida',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4429084.png&w=350&h=254',
    pass_att: 2,
    comp: 1,
    pass_yards: 9,
    comp_percent: 50,
    qb_rtng: 62.5,
    rush_att: 4,
    rush_yds: -1,
    rush_ypc: -0.2,
    rec: 1,
    rec_yards: 9,
    rec_ypc: 9.0
  },
  {
    name: 'Anthony Gould',
    number: '6',
    position: 'WR',
    exp: 2,
    status: 'Active',
    college: 'Oregon State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4429684.png&w=350&h=254',
    rec: 1,
    rec_yards: 3,
    rec_ypc: 3.0,
    pr_ret: 12,
    pr_fc: 6,
    pr_lng: 21,
    pr_yds: 10.9,
    kr_ret: 23,
    kr_fc: 0,
    kr_yds: 596,
    kr_yds_ret: 25.9,
    kr_lng: 39
  },
  {
    name: 'Charvarius Ward',
    number: '7',
    position: 'CB',
    exp: 8,
    status: 'Active',
    college: 'Middle Tennessee State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4037361.png&w=350&h=254',
    tackles: 21,
    solo_tackles: 14,
    assist: 7
  },
  {
    name: 'Rigoberto Sanchez',
    number: '8',
    position: 'P',
    exp: 9,
    status: 'Active',
    college: 'Hawaii',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3914922.png&w=350&h=254',
    punt: 29,
    punt_yards: 1434,
    punt_in20: 15,
    punt_avg: 49.4,
    punt_lng: 59
  },
  {
    name: 'Coleman Owen',
    number: '9',
    position: 'WR',
    exp: 0,
    status: 'PS',
    college: 'Ohio',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4578436.png&w=350&h=254',
  },
  {
    name: 'Blake Grupe',
    number: '10',
    position: 'K',
    exp:3,
    status: 'Active',
    college: 'Notre Dame',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4259619.png&w=350&h=254'
  },
  {
    name: 'Michael Pittman Jr.',
    number: '11',
    position: 'WR',
    exp: 6,
    status: 'Active',
    college: 'USC',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4035687.png&w=350&h=254',
    rec: 60,
    rec_yards: 620,
    rec_ypc: 10.3,
    rec_td: 7
  },
  {
    name: 'Laquon Treadwell',
    number: '13',
    position: 'WR',
    exp: 9,
    status: 'Active',
    college: 'Mississippi',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3051889.png&w=350&h=254'
  },
  {
    name: 'Alec Pierce',
    number: '14',
    position: 'WR',
    exp: 4,
    status: 'Active',
    college: 'Cincinnati',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4360078.png&w=350&h=254',
    rec: 33,
    rec_yards: 689,
    rec_ypc: 20.9,
    rec_td: 2
  },
  {
    name: 'Riley Leonard',
    number: '15',
    position: 'QB',
    exp: 0,
    status: 'Active',
    college: 'Notre Dame',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4683423.png&w=350&h=254',
    pass_att: 2,
    comp: 0,
    pass_yards: 0,
    pass_td: 0,
    comp_percent: 0.0,
    int: 0,
    qb_rtng: 39.6,
    rush_att: 1,
    rush_yds: 1,
    rush_ypc: 1.0
  },
  {
    name: 'Ashton Dulin',
    number: '16',
    position: 'WR',
    exp: 7,
    status: 'IR',
    college: 'Malone University',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4061956.png&w=350&h=254',
    rec: 5,
    rec_yards: 106,
    rec_ypc: 21.2,
    rush_att: 3,
    rush_yds: 44,
    rush_ypc: 14.7,
    tackles: 3,
    solo_tackles: 2,
    assist: 1,
    kr_ret: 11,
    kr_fc: 0,
    kr_yds: 328,
    kr_yds_ret: 29.8,
    kr_lng: 50
  },
  {
    name: 'Daniel Jones',
    number: '17',
    position: 'QB',
    exp: 7,
    status: 'Active',
    college: 'Duke',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3917792.png&w=350&h=254',
    pass_att: 377,
    comp: 256,
    pass_yards: 3041,
    pass_td: 19,
    comp_percent: 67.9,
    sacked: 22,
    int: 7,
    qb_rtng: 101.3,
    rush_att: 44,
    rush_yds: 160,
    rush_ypc: 3.6,
    rush_td: 5
  },
  {
    name: 'Nick Cross',
    number: '20',
    position: 'S',
    exp: 4,
    status: 'Active',
    college: 'Maryland',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4426403.png&w=350&h=254',
    tackles: 83,
    solo_tackles: 50,
    assist: 33,
    def_sacks: 2.5,
    def_int: 1
  },
  {
    name: 'DJ Giddens',
    number: '21',
    position: 'RB',
    exp: 0,
    status: 'Active',
    college: 'Kansas State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4874509.png&w=350&h=254',
    rush_att: 18,
    rush_yds: 66,
    rush_ypc: 3.7,
    rush_td: 0
  },
  {
    name: 'Kenny Moore II',
    number: '23',
    position: 'CB',
    exp: 9,
    status: 'Active',
    college: 'Valdosta State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4218312.png&w=350&h=254',
    tackles: 36,
    solo_tackles: 20,
    assist: 16,
    def_sacks: 1.5,
    def_fumble: 2,
    def_int: 1,
    def_td: 1
  },
  {
    name: 'Rodney Thomas II',
    number: '25',
    position: 'S',
    exp: 4,
    status: 'Active',
    college: 'Yale',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4248455.png&w=350&h=254',
    rush_att: 1,
    rush_yds: 3,
    rush_ypc: 3.0,
    tackles: 16,
    solo_tackles: 10,
    assist: 6
  },
  {
    name: 'Ameer Abdulllah',
    number: '26',
    position: 'RB',
    exp: 11,
    status: 'Active',
    college: 'Nebraska',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2576336.png&w=350&h=254',
    rec: 5,
    rec_yards: 30,
    rec_ypc: 6.0,
    rush_att: 8,
    rush_yds: 40,
    rush_ypc: 5.0,
    rush_td: 1,
    kr_ret: 11,
    kr_fc: 0,
    kr_yds: 358,
    kr_yds_ret: 32.6,
    kr_lng: 81
  },
  {
    name: 'Justin Walley',
    number: '27',
    position: 'CB',
    exp: 0,
    status: 'IR',
    college: 'Minnesota',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4682909.png&w=350&h=254',
  },
  {
    name: 'Jonathan Taylor',
    number: '28',
    position: 'RB',
    exp: 6,
    status: 'Active',
    college: 'Wisconsin',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4242335.png&w=350&h=254',
    rush_att: 226,
    rush_yds: 1282,
    rush_ypc: 5.7,
    rush_td: 15,
    rec: 35,
    rec_yards: 304,
    rec_ypc: 8.7,
    rec_td: 2
  },
  {
    name: 'Mekhi Blackmon',
    number: '29',
    position: 'CB',
    exp: 3,
    status: 'Active',
    college: 'USC',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4360677.png&w=350&h=254',
    tackles: 50,
    solo_tackles: 39,
    assist: 11,
    def_sacks: 1,
    def_int: 2
  },
  {
    name: 'Hunter Wohler',
    number: '30',
    position: 'S',
    exp: 0,
    status: 'IR',
    college: 'Wisconsin',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4432789.png&w=350&h=254',
  },
  {
    name: 'Tyler Goodson',
    number: '31',
    position: 'RB',
    exp: 3,
    status: 'Active',
    college: 'Iowa',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4429676.png&w=350&h=254',
    rush_att: 5,
    rush_yds: 12,
    rush_ypc: 2.4,
    rec: 2,
    rec_yards: 8,
    rec_ypc: 4.0
  },
  {
    name: 'Daniel Scott',
    number: '32',
    position: 'S',
    exp: 3,
    status: 'IR',
    college: 'California',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4242415.png&w=350&h=254'
  },
  {
    name: 'Mike Hilton',
    number: '33',
    position: 'CB',
    exp: 9,
    status: 'PSI',
    college: 'Mississippi',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2980383.png&w=350&h=254',
    tackles: 5,
    solo_tackles: 4,
    assist: 1
  },
  {
     name: 'Ben Nikkel',
     number: '34',
     position: 'S',
     exp: 1,
     status: 'PS',
     college: 'Iowa State',
     photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4874465.png&w=350&h=254'
  },
  {
    name: 'Johnathan Edwards',
    number: '35',
    position: 'CB',
    exp: 0,
    status: 'Active',
    college: 'Tulane',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4695991.png&w=350&h=254',
    tackles: 16,
    solo_tackles: 12,
    assist: 4
  },
  {
    name: 'Salvon Ahmed',
    number: '36',
    position: 'RB',
    exp: 5,
    status: 'IR',
    college: 'Washington',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4243315.png&w=350&h=254'
  },
  {
    name: 'Reuben Lowery III',
    number: '36',
    position: 'S',
    exp: 0,
    status: 'Active',
    college: 'Tennessee-Chattanooga',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4692970.png&w=350&h=254',
  },
  {
    name: 'Ulysses Bentley IV',
    number: '37',
    position: 'RB',
    exp: 0,
    status: 'PS',
    college: 'Mississippi',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4426689.png&w=350&h=254',
    rush_att: 1,
    rush_yds: 0,
    rush_ypc: 0.0
  },
  {
    name: 'Chris Lammons',
    number: '38',
    position: 'CB',
    exp: 5,
    status: 'Active',
    college: 'South Carolina',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3128630.png&w=350&h=254',
    tackles: 17,
    solo_tackles: 14,
    assist: 3,
    def_int: 1
  },
  {
    name: 'George Odum',
    number: '39',
    position: 'S',
    exp: 8,
    status: 'Active',
    college: 'Central Arkansas',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3050199.png&w=350&h=254',
  },
  {
    name: 'Jaylon Jones',
    number: '40',
    position: 'CB',
    exp: 3,
    status: 'Active',
    college: 'Texas A&M',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4685145.png&w=350&h=254',
  },
  {
    name: 'Trey Washington',
    number: '41',
    position: 'S',
    exp: 0,
    status: 'PS',
    college: 'Mississippi',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4599160.png&w=350&h=254',
  },
  {
    name: 'Cameron Mitchell',
    number: '43',
    position: 'CB',
    exp: 3,
    status: 'PS',
    college: 'Northwestern',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4569607.png&w=350&h=254',
  },
  {
    name: 'Zaire Franklin',
    number: '44',
    position: 'LB',
    exp: 8,
    status: 'Active',
    college: 'Syracuse',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3124005.png&w=350&h=254',
    tackles: 87,
    solo_tackles: 43,
    assist: 44,
    def_sacks: 2,
    def_fumble: 1
  },
  {
    name: 'Luke Rhodes',
    number: '46',
    position: 'LS',
    exp: 9,
    status: 'Active',
    college: 'William & Mary',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2566045.png&w=350&h=254'
  },
  {
    name: 'Sean McKeon',
    number: '49',
    position: 'TE',
    exp: 5,
    status: 'PS',
    college: 'Michigan',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4036275.png&w=350&h=254'
  },
  {
    name: 'Segun Olubi',
    number: '50',
    position: 'LB',
    exp: 3,
    status: 'Active',
    college: 'San Diego State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4260703.png&w=350&h=254',
    tackles: 6,
    solo_tackles: 5,
    assist: 1
  },
  {
    name: 'Kwity Paye',
    number: '51',
    position: 'DE',
    exp: 5,
    status: 'Active',
    college: 'Michigan',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4258194.png&w=350&h=254',
    tackles: 31,
    solo_tackles: 13,
    assist: 18,
    def_sacks: 3.5
  },
  {
    name: 'Samson Ebukam',
    number: '52',
    position: 'DE',
    exp: 9,
    status: 'Active',
    college: 'Eastern Washington',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3045527.png&w=350&h=254',
    tackles: 18,
    solo_tackles: 13,
    assist: 5,
    def_sacks: 2
  },
  {
    name: 'Germaine Pratt',
    number: '53',
    position: 'LB',
    exp: 7,
    status: 'Active',
    college: 'N.C. State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3116724.png&w=350&h=254',
    tackles: 67,
    solo_tackles: 40,
    assist: 27
  },
  {
    name: 'Jacob Phillips',
    number: '54',
    position: 'LB',
    exp: 4,
    status: 'IR',
    college: 'LSU',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4242206.png&w=350&h=254'
  },
  {
    name: 'Anthony Walker',
    number: '54',
    position: 'LB',
    exp: 9,
    status: 'PS',
    college: 'Northwestern',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3045251.png&w=350&h=254'
  },
  {
    name: 'Chad Muma',
    number: '55',
    position: 'LB',
    exp: 4,
    status: 'PS',
    college: 'Wyoming',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4361707.png&w=350&h=254'
  },
  {
    name: 'Quenton Nelson',
    number: '56',
    position: 'G',
    exp: 8,
    status: 'Active',
    college: 'Notre Dame',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3129308.png&w=350&h=254'
  },
  {
    name: 'Jaylon Carlies',
    number: '57',
    position: 'LB',
    exp: 2,
    status: 'IR',
    college: 'Missouri',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4601021.png&w=350&h=254',
  },
  {
    name: 'Austin Ajiake',
    number: '58',
    position: 'LB',
    exp: 1,
    status: 'Active',
    college: 'UNLV',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4374171.png&w=350&h=254',
    tackles: 27,
    solo_tackles: 12,
    assist: 15,
    def_sacks: 0.5
  },
  {
    name: 'Buddy Johnson',
    number: '59',
    position: 'LB',
    exp: 4,
    status: 'Active',
    college: 'Texas A&M',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4240900.png&w=350&h=254'
  },
  {
    name: 'Tanor Bortolini',
    number: '60',
    position: 'G',
    exp: 2,
    status: 'Active',
    college: 'Wisconsin',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4430957.png&w=350&h=254'
  },
  {
    name: 'Viliami Fehoko Jr.',
    number: '61',
    position: 'DE',
    exp: 2,
    status: 'PS',
    college: 'San Jose State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4374148.png&w=350&h=254'
  },
  {
    name: 'Danny Pinter',
    number: '63',
    position: 'G',
    exp: 6,
    status: 'Active',
    college: 'Ball State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3915470.png&w=350&h=254'
  },
  {
    name: 'Josh Sills',
    number: '66',
    position: 'G',
    exp: 3,
    status: 'PS',
    college: 'Oklahoma State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4039243.png&w=350&h=254'
  },
  {
    name: 'Luke Tenuta',
    number: '67',
    position: 'T',
    exp: 3,
    status: 'Active',
    college: 'Virginia Tech',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4361979.png&w=350&h=254'
  },
  {
    name: 'Dalton Tucker',
    number: '68',
    position: 'G',
    exp: 2,
    status: 'Active',
    college: 'Marshall',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4370363.png&w=350&h=254'
  },
  {
    name: 'Matt Goncalves',
    number: '71',
    position: 'T',
    exp: 2,
    status: 'Active',
    college: 'Pittsburgh',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4427298.png&w=350&h=254'
  },
  {
    name: 'Braden Smith',
    number: '72',
    position: 'T',
    exp: 8,
    status: 'Active',
    college: 'Auburn',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3121595.png&w=350&h=254'
  },
  {
    name: 'Blake Freeland',
    number: '73',
    position: 'T',
    exp: 3,
    status: 'IR',
    college: 'BYU',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4429636.png&w=350&h=254'
  },
  {
    name: 'Durell Nchami',
    number: '74',
    position: 'DE',
    exp: 1,
    status: 'PS',
    college: 'Maryland',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4360638.png&w=350&h=254'
  },
  {
    name: 'Jalen Travis',
    number: '75',
    position: 'T',
    exp: 0,
    status: 'Active',
    college: 'Iowa State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4892240.png&w=350&h=254'
  },
  {
    name: 'Jack Wilson',
    number: '76',
    position: 'T',
    exp: 1,
    status: 'IR',
    college: 'Washington State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/504844.png&w=350&h=254'
  },
  {
    name: 'Bayron Matos',
    number: '78',
    position: 'T',
    exp: 1,
    status: 'PS',
    college: 'University of South Florida',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4612507.png&w=350&h=254'
  },
  {
    name: 'Bernhard Raimann',
    number: '79',
    position: 'T',
    exp: 4,
    status: 'Active',
    college: 'Central Michigan',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4362580.png&w=350&h=254',
  },
  { 
     name: 'Mo Alie-Cox', 
     number: '81', 
     position: 'TE', 
     exp: 8, 
     status: 'Active', 
     college: 'Virginia Commonwealth', 
     photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2998565.png&w=350&h=254',
     rec: 5,
     rec_yards: 59,
     rec_ypc: 11.8,
     rec_td: 0
  },
  {
    name: 'Eli Pancol',
    number: '83',
    position: 'WR',
    exp: 0,
    status: 'WR',
    college: 'Duke',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4430288.png&w=350&h=254'
  },
  {
    name: 'Tyler Warren',
    number: '84',
    position: 'TE',
    exp: 0,
    status: 'Active',
    college: 'Penn State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4431459.png&w=350&h=254',
    pass_att: 1,
    comp: 0,
    pass_yards: 0,
    comp_percent: 0,
    qb_rtng: 39.6,
    rush_att: 5,
    rush_yds: 6,
    rush_ypc: 1.2,
    rush_td: 1,
    rec: 58,
    rec_yards: 684,
    rec_ypc: 11.8,
    rec_td: 4
  },
  {
    name: 'Drew Ogletree',
    number: '85',
    position: 'TE',
    exp: 4,
    status: 'Active',
    college: 'Youngstown State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4722908.png&w=350&h=254',
    tackles: 2,
    solo_tackles: 1,
    assist: 1,
    rec: 3,
    rec_yards: 16,
    rec_ypc: 5.3,
    rec_td: 1
  },
  {
    name: 'Will Mallory',
    number: '86',
    position: 'TE',
    exp: 3,
    status: 'Active',
    college: 'Miami',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4362523.png&w=350&h=254',
  },
  {
    name: 'Grover Stewart',
    number: '90',
    position: 'DT',
    exp: 9,
    status: 'Active',
    college: 'Albany State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4058825.png&w=350&h=254',
    tackles: 42,
    solo_tackles: 18,
    assist: 24,
    def_int: 1,
    def_sacks: 0.5
  },
  {
    name: 'JT Tuimoloau',
    number: '91',
    position: 'DE',
    exp: 0,
    status: 'Active',
    college: 'Ohio State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4566154.png&w=350&h=254',
  },
  {
    name: 'Neville Gallimore',
    number: '92',
    position: 'DT',
    exp: 6,
    status: 'Active',
    college: 'Oklahoma',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3892883.png&w=350&h=254',
    tackles: 29,
    solo_tackles: 12,
    assist: 17,
    def_sacks: 3.5
  },
  {
    name: 'Tim Smith',
    number: '93',
    position: 'DT',
    exp: 0,
    status: 'PS',
    college: 'Alabama',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4692033.png&w=350&h=254',
  },
  {
    name: 'Tyquan Lewis',
    number: '94',
    position: 'DE',
    exp: 8,
    status: 'Active',
    college: 'Ohio State',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3040513.png&w=350&h=254',
    tackles: 6,
    solo_tackles: 5,
    assist: 1,
    def_sacks: 3
  },
  {
    name: 'Adetomiwa Adebawore',
    number: '95',
    position: 'DT',
    exp: 3,
    status: 'Active',
    college: 'Northwestern',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4427635.png&w=350&h=254',
    tackles: 25,
    solo_tackles: 9,
    assist: 16,
    def_sacks: 3.0
  },
  {
    name: 'Chris Wormley',
    number: '96',
    position: 'DT',
    exp: 8,
    status: 'Active',
    college: 'Michigan',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2977615.png&w=350&h=254',
    tackles: 2,
    solo_tackles: 2,
    def_sacks: 1.0
  },
  {
    name: 'Laiatu Latu',
    number: '97',
    position: 'DE',
    exp: 1,
    status: 'Active',
    college: 'UCLA',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4426473.png&w=350&h=254',
    tackles: 33,
    solo_tackles: 17,
    assist: 16,
    def_sacks: 5.5,
    def_int: 3
  },
  { 
    name: 'Eric Johnson II', 
    number: '98', 
    position: 'DT', 
    exp: 2, 
    status: 'Active', 
    college: 'Missouri State', 
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4050971.png&w=350&h=254',
    tackles: 2,
    solo_tackles: 2
  },
  {
    name: 'DeForest Buckner',
    number: '99',
    position: 'DT',
    exp: 10,
    status: 'IR',
    college: 'Oregon',
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2971282.png&w=350&h=254',
    tackles: 42,
    solo_tackles: 26,
    assist: 16,
    def_sacks: 4
  }
])
