Schedule.create!([
  # Regular Season Games
  {
    week: '1',
    gamedate: 'Sun 09/07',
    gametime: '1:00PM',
    location: 'home',
    result: 'W',
    score: '33 - 8',
    oppcity: 'Miami',
    oppname: 'Dolphins',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/mia.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    week: '2',
    gamedate: 'Sun 09/14',
    gametime: '4:05PM',
    location: 'home',
    result: 'W',
    score: '29 - 28',
    oppcity: 'Denver',
    oppname: 'Broncos',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/den.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    week: '3',
    gamedate: 'Sun 09/21',
    gametime: '1:00PM',
    location: 'away',
    result: 'W',
    score: '41 - 20',
    oppcity: 'Tennessee',
    oppname: 'Titans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ten.png&h=200&w=200',
    stadium: 'Nissan Stadium',
    map: 'https://maps.app.goo.gl/4ptMhmc13gTWMYri7'
  },
  {
    week: '4',
    gamedate: 'Sun 09/28',
    gametime: '4:05PM',
    location: 'away',
    result: 'L',
    score: '20 - 27',
    oppcity: 'Los Angeles',
    oppname: 'Rams',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/lar.png&h=200&w=200',
    stadium: 'SoFi Stadium',
    map: 'https://maps.app.goo.gl/iXXVb5WpnrazZPpm8'
  },
  {
    week: '5',
    gamedate: 'Sun 10/05',
    gametime: '1:00PM',
    location: 'home',
    result: 'W',
    score: '40 - 6',
    oppcity: 'Las Vegas',
    oppname: 'Raiders',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/lv.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    week: '6',
    gamedate: 'Sun 10/12',
    gametime: '1:00PM',
    location: 'home',
    result: 'W',
    score: '31 - 27',
    oppcity: 'Arizona',
    oppname: 'Cardinals',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ari.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    week: '7',
    gamedate: 'Sun 10/19',
    gametime: '4:05PM',
    location: 'away',
    result: 'W',
    score: '38 - 24',
    oppcity: 'Los Angeles',
    oppname: 'Chargers',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/lac.png&h=200&w=200',
    stadium: 'SoFi Stadium',
    map: 'https://maps.app.goo.gl/iXXVb5WpnrazZPpm8'
  },
  {
    week: '8',
    gamedate: 'Sun 10/26',
    gametime: '4:25PM',
    location: 'home',
    result: 'W',
    score: '38 - 14',
    oppcity: 'Tennessee',
    oppname: 'Titans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ten.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    week: '9',
    gamedate: 'Sun 11/02',
    gametime: '1:00PM',
    location: 'away',
    result: 'L',
    score: '20 - 27',
    oppcity: 'Pittsburgh',
    oppname: 'Steelers',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/pit.png&h=200&w=200',
    stadium: 'Acrisure Stadium',
    map: 'https://maps.app.goo.gl/KrZ3iqwyfuduCiXw7'
  },
  {
    week: '10',
    gamedate: 'Sun 11/09',
    gametime: '9:30AM',
    location: 'away',
    result: 'W',
    score: '31 - 25',
    oppcity: 'Atlanta',
    oppname: 'Falcons',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/atl.png&h=200&w=200',
    stadium: 'Olympic Stadium',
    map: 'https://maps.app.goo.gl/RhJ3uc8mHThy4w8r7'
  },
  {
    week: '11',
    oppname: 'Bye',
  },
  {
    week: '12',
    gamedate: 'Sun 11/23',
    gametime: '1:00PM',
    location: 'away',
    result: 'L',
    score: '20 - 23',
    oppcity: 'Kansas City',
    oppname: 'Chiefs',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/kc.png&h=200&w=200',
    stadium: 'Arrowhead Stadium',
    map: 'https://maps.app.goo.gl/GdA5S7zrgTa3nTn18'
  },
  {
    week: '13',
    gamedate: 'Sun 11/30',
    gametime: '1:00PM',
    location: 'home',
    result: 'L',
    score: '16 - 20',
    oppcity: 'Houston',
    oppname: 'Texans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/hou.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    week: '14',
    gamedate: 'Sun 12/07',
    gametime: '1:00PM',
    location: 'away',
    result: 'L',
    score: '19 - 36',
    oppcity: 'Jacksonville',
    oppname: 'Jaguars',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/jax.png&h=200&w=200',
    stadium: 'Everbank Stadium',
    map: 'https://maps.app.goo.gl/UTR1xnoTcK1bAGtK9'
  },
  {
    week: '15',
    gamedate: 'Sun 12/14',
    gametime: '4:25PM',
    location: 'away',
    result: 'L',
    score: '16 - 18',
    oppcity: 'Seattle',
    oppname: 'Seahawks',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/sea.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/9rRk2X4Hnmq99L468'
  },
  {
    week: '16',
    gamedate: 'Mon 12/22',
    gametime: '8:15PM',
    location: 'home',
    result: 'L',
    score: '27 - 48',
    oppcity: 'San Francisco',
    oppname: '49ers',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/sf.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    week: '17',
    gamedate: 'Sun 12/28',
    gametime: '1:00PM',
    location: 'home',
    result: '',
    score: '',
    oppcity: 'Jacksonville',
    oppname: 'Jaguars',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/jax.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    week: '18',
    gamedate: 'TBD',
    gametime: 'TBD',
    location: 'away',
    result: '',
    score: '',
    oppcity: 'Houston',
    oppname: 'Texans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/hou.png&h=200&w=200',
    stadium: 'NRG Stadium',
    map: 'https://maps.app.goo.gl/Rn65v4AKkgNgHQDr7'
  }
])