Schedule.create!([
  # Regular Season Games
  { 
    week: '1',
    gamedate: '10-09-2023',
    gametime: '1:00PM',
    location: 'home',
    result: 'L',
    score: '21-31',
    oppname: 'Jacksonville Jaguars',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/jax.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  { 
    week: '2',
    gamedate: '17-09-2023',
    gametime: '1:00PM',
    location: 'away',
    result: 'W',
    score: '31-20 ',
    oppname: 'Houston Texans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/hou.png&h=200&w=200',
    stadium: 'NRG Stadium',
    map: 'https://maps.app.goo.gl/Rn65v4AKkgNgHQDr7'
  },
  { 
    week: '3',
    gamedate: '24-09-2023',
    gametime: '1:00PM',
    location: 'away',
    result: 'W',
    score: '22-19',
    oppname: 'Baltimore Ravens',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/bal.png&h=200&w=200',
    stadium: 'M&T Bank Stadium',
    map: 'https://maps.app.goo.gl/Td2KScyke6YF4rj9A'
  },
  { 
    week: '4',
    gamedate: '01-10-2023',
    gametime: '1:00PM',
    location: 'home',
    result: 'L',
    score: '23-29',
    oppname: 'LA Rams',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/lar.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  { 
    week: '5',
    gamedate: '08-10-2023',
    gametime: '1:00PM',
    location: 'home',
    result: 'W',
    score: '23-16',
    oppname: 'Tennessee Titans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ten.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  { 
    week: '6',
    gamedate: '15-10-2023',
    gametime: '1:00PM',
    location: 'away',
    result: 'L',
    score: '20-37',
    oppname: 'Jacksonville Jaguars',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/jax.png&h=200&w=200',
    stadium: 'Everbank Stadium',
    map: 'https://maps.app.goo.gl/UTR1xnoTcK1bAGtK9'
  },
  { 
    week: '7',
    gamedate: '22-10-2023',
    gametime: '1:00PM',
    location: 'home',
    result: 'L',
    score: '38-39',
    oppname: 'Cleveland Browns',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/cle.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  { 
    week: '8',
    gamedate: '29-10-2023',
    gametime: '1:00PM',
    location: 'home',
    result: '',
    score: '', oppname: 'New Orleans Saints',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/no.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  { 
    week: '9',
    gamedate: '05-11-2023',
    gametime: '4:05PM',
    location: 'away',
    result: '',
    score: '',
    oppname: 'Carolina Panthers',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/car.png&h=200&w=200',
    stadium: 'Bank of America Stadium',
    map: 'https://maps.app.goo.gl/fh1A1RGx3AvJzhcdA'
  },
  { 
    week: '10',
    gamedate: '12-11-2023',
    gametime: '9:30AM',
    location: 'away',
    result: '',
    score: '',
    oppname: 'New England Patriots',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ne.png&h=200&w=200',
    stadium: 'Deutsche Bank Park',
    map: 'https://maps.app.goo.gl/PaMFTEi8Dj2wFBYT8'
  },
  { 
    week: '11',
    oppname: 'Bye'
  },
  {
    week: '12',
    gamedate: '26-11-2023',
    gametime: '1:00PM',
    location: 'home',
    result: '',
    score: '',
    oppname: 'Tampa Bay Buccaneers',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/tb.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  { 
    week: '13',
    gamedate: '03-12-2023',
    gametime: '1:00PM',
    location: 'away',
    result: '',
    score: '',
    oppname: 'Tennessee Titans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ten.png&h=200&w=200',
    stadium: 'Nissan Stadium',
    map: 'https://maps.app.goo.gl/4ptMhmc13gTWMYri7'
  },
  { 
    week: '14',
    gamedate: '10-12-2023',
    gametime: '1:00PM',
    location: 'away',
    result: '',
    score: '',
    oppname: 'Cincinnati Bengals',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/cin.png&h=200&w=200',
    stadium: 'Paycor Stadium',
    map: 'https://maps.app.goo.gl/r72zDuZE8yskC4mYA'
  },
  { 
    week: '15',
    gamedate: 'TBD',
    gametime: 'TBD',
    location: 'home',
    result: '',
    score: '',
    oppname: 'Pittsburgh Steelers',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/pit.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  { 
    week: '16',
    gamedate: '24-12-2023',
    gametime: '1:00PM',
    location: 'away',
    result: '',
    score: '',
    oppname: 'Atlanta Falcons',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/atl.png&h=200&w=200',
    stadium: 'Mercedes-Benz Stadium',
    map: 'https://maps.app.goo.gl/fXoJJ1LqZDmyNbDD7'
  },
  { 
    week: '17',
    gamedate: '31-12-2023',
    gametime: '1:00PM',
    location: 'home',
    result: '',
    score: '',
    oppname: 'Las Vegas Raiders',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/lv.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  { 
    week: '18',
    gamedate: 'TBD',
    gametime: 'TBD',
    location: 'home',
    result: '',
    score: '',
    oppname: 'Houston Texans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/hou.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  }
])