[build]
  base = ""
  command = """
    gem uninstall -aIx bundler
    gem install bundler -v "2.5.3"
    bundle install
    bundle exec jekyll build
  """
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.3.5"

[build.processing]
  skip_processing = false