databases:
  - name: coltsrailsdb
    databaseName: coltsrailsdb
    user: usmcamgrimm

services:
  - type: web
    name: coltsrails
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: coltsrailsdb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false