class AddStatsColumnsToPups < ActiveRecord::Migration[7.0]
  def change
    add_column :pups, :pass_att, :integer
    add_column :pups, :comp, :integer
    add_column :pups, :pass_yards, :integer
    add_column :pups, :pass_td, :integer
    add_column :pups, :int, :integer
    add_column :pups, :pass_sck, :integer
    add_column :pups, :rush_att, :integer
    add_column :pups, :rush_yds, :integer
    add_column :pups, :rush_td, :integer
    add_column :pups, :rec, :integer
    add_column :pups, :rec_yards, :integer
    add_column :pups, :rec_td, :integer
    add_column :pups, :tackles, :integer
    add_column :pups, :solo_tackles, :integer
    add_column :pups, :def_sacks, :integer
    add_column :pups, :safety, :integer
    add_column :pups, :def_fumble, :integer
    add_column :pups, :def_int, :integer
    add_column :pups, :def_td, :integer
    add_column :pups, :fg_1to19, :integer
    add_column :pups, :fg_20to29, :integer
    add_column :pups, :fg_30to39, :integer
    add_column :pups, :fg_40to49, :integer
    add_column :pups, :fg_50to59, :integer
    add_column :pups, :fg_60Plus, :integer
    add_column :pups, :punt, :integer
    add_column :pups, :punt_yards, :integer
    add_column :pups, :punt_in20, :integer
    add_column :pups, :punt_blk, :integer
    add_column :pups, :net_avg, :integer
    add_column :pups, :pr_ret, :integer
    add_column :pups, :pr_yds_ret, :integer
    add_column :pups, :pr_td, :integer
    add_column :pups, :kr_ret, :integer
    add_column :pups, :kr_yards, :integer
    add_column :pups, :kr_long, :integer
    add_column :pups, :kr_td, :integer
  end
end
